#! /usr/bin/python3

from __future__ import print_function

from launchpadlib.launchpad import Launchpad
from optparse import OptionParser


parser = OptionParser(usage="%prog OWNER/NAME")
_, args = parser.parse_args()
if not args:
    parser.error("must provide a PPA owner/name")
owner_name, ppa_name = args[0].split("/", 1)
lp = Launchpad.login_anonymously('livecd-rootfs', 'production', version='devel')
print(lp.people(owner_name).getPPAByName(name=ppa_name).signing_key_fingerprint)
